matrixbot/plugins/trac.py

Send notice events instead of message events when providint ticket information. Using normal messages for automated messages is distracting for on-going  conversations, and moreover the [Matrix spec](http://matrix.org/docs/spec/client_server/r0.2.0.html#m-notice) explicitly mandates using `m.notice` events:
> It is intended to be used by automated clients, such as bots, bridges, and other entities, rather than humans.

Trac: Send notices instead of normal messages

---

README.md
matrixbot/plugins/wktestbotsfeeder.py

It works similarly to `plugin/wkbotsfeeder.py`.
Given a list of test bots, the script checks the 'text' value of the latest build for each bot. If the string 'Early exit' is found, the plugin reports a failure. The plugin reports recoveries on the next build after a failure.

Plugin for WebKit Test Bots

---

matrixbot/plugins/wktestbotsfeeder.py

The plugin is considering that whenever a build didn't fail, then the bot recovered.
However, there's a case where this leads to a false positive and it's the case when one or more build failed and then the next one was ended with an exception (by pressing Cancel in the UI, for instance). In that case, the plugin considers the bot has recovered but it should remain on the same state as before.
For instance, this build was considered a recovering after several failures https://build.webkit.org/builders/GTK%20Linux%2064-bit%20Release%20%28Tests%29/builds/13504. Another one: https://build.webkit.org/builders/GTK%20Linux%2064-bit%20Debug%20%28Tests%29
In summary, I think the way of managing this "exception" state is a neutral value.

Do not recover if exception

---

matrixbot/matrix.py

This makes the join command a little bit friendlier.
**Note**: I have not been able to test this. Sorry!

When no domain specified with join, use local domain

---

cfg/matrix-bot.cfg.example
matrixbot/plugins/wkbotsfeeder.py

There are builders, such as the JSCOnly builders, that build and test. We use this plugin mostly for monitor that status of bots that build only. I would like to determine whether a JSCOnly bot was successful by evaluating the status of the 'compile-webkit' step, and not the general status of the build.
To do that, builders can now define a 'target_step' to watch and what text to search for to determine the step was successful. Example:
```python
"builders": {
"JSCOnly Linux MIPS32el Release",
"last_buildjob_url_squema": "https://build.webkit.org/builders/%(builder_name)s/builds/%(last_buildjob)s",
"builds_url_squema": "https://build.webkit.org/json/builders/%(builder_name)s/builds?select=-2&as_text=1",
"builder_name": "JSCOnly Linux MIPS32el Release",
"only_failures": False, …
```

Allow builders define what building step to monitor 

---

matrixbot/plugins/wkbotsfeeder.py

Since #26 landed, recovery status for a bot is not reported just once, but always. I think I introduced an error in the computation of the condition that sets the recovery flag.

Fix condition that sets recovery status

---

matrixbot/plugins/wkbotsfeeder.py

Another glitch introduced after the refactorization in https://github.com/psaavedra/matrix-bot/commit/fb24c70e2d7be5f736702e0a699b01da0a019724
The logic that checks whether to send a message or not wasn't translated correctly. Right now, the plugin is reporting 'success' statuses for every build. The reason is that the condition that checks 'only-failures' (True in the plugin) should be "not only-failures", so the plugin doesn't send success messages for every build.

wkbotsfeeder.py: only-failures logic was inversed

---

matrixbot/matrix.py

Support for m.room.aliases events was removed in Synapse 1.10

Fix alias issue with new versions

---

README.md

In the install instructions, dependency of "python-dateutil" is missing.

README.md: Add missing dependency in install instructions

---

matrixbot/matrix.py

Without spaces, the names of the aliases for the rooms are correctly
interpreted and allow clients to interpret them as clickable and
navigable links.

Fix: Remove spaces on room aliases before listing them

---

matrixbot/matrix.py

There's a runtime error if keyword 'super_users' is not defined in a configuration file.

Fix runtime error 'super_users' not in configuration file

---

matrixbot/plugins/wkbotsfeeder.py
matrixbot/utils.py

Recently build.webkit.org has updated to buildbot 2.10, which uses a new JSON API (See: http://docs.buildbot.net/current/developer/rest.html).
This PR is WIP. I'm testing these changes locally, but I need to wait for results to verify it's working correctly.

Adapt WKBotsFeeder plugin to new buildbot API

---

matrixbot/utils.py

This patch makes possible a configuration like this:
```
settings["DEFAULT"] = {
"loglevel": 10,
"logfile": "/dev/stdout",
"period": 3,
}
```

Allow one to use /dev/stdout or /dev/stderr as logfile

---

cfg/matrix-bot.cfg.example-super-users
matrixbot/matrix.py
matrixbot/utils.py

This option allows one to disable the interactive commands in the bot. This is useful to run noninteractive bots.

Add commands.enable setting

---

matrixbot/plugins/wkbotsfeeder.py

The function `format` was previously refactored to `pp` and moved to _utils.py_.

wkbotsfeeder: Rename 'self.format' to 'pp'

---

matrixbot/plugins/wkbotsfeeder.py

Sometimes we want to observe a particular step of a build instead of the general state of the build. For instance, we might be interested in observing the compilation step of a builder, and determine success based on that step.

wkbotsfeeder: Allow a builder determine success depending on the value of a build step

---

matrixbot/ldap.py
matrixbot/matrix.py
matrixbot/utils.py
tools/matrix-bot

**Motivation:**
The main loop logic is synchronous even when many logic could be executed in pararell
**Change:**
rework of the code using async/await 
**Other considerations**:
This change also requires the python environment updated to 3.7 (at least): https://github.com/psaavedra/matrix-bot/pull/45
* This change address the issue https://github.com/psaavedra/matrix-bot/issues/22
**How to set the environment**:
```
cd matrix-bot
virtualenv -p python3 test_env
. test_env/bin/activate
export PYTHONPATH=$(pwd):$PYTHONPATH
tools/matrix-bot  -c matrixbot.conf
```

Use async/await to run the main loop of the matrix-bot

---

cfg/matrix-bot.cfg.example
matrixbot/matrix.py
matrixbot/utils.py
setup.py
tools/matrix-digest

DEPENDS: https://github.com/psaavedra/matrix-bot/pull/54
A convenient tool to sends the DAYS backlog activity of the ROOM to the
SENDTO mailbox. Ideal to use as a cronjob.
There is an maximum harcoded value of 5000 messages.
Example of use:
```
usage: matrix-digest [-h] [-c CONFFILE] [-s SENDTO] [-d DAYS] ROOM
positional arguments:
ROOM                  Room
optional arguments:
-h, --help            show this help message and exit
-c CONFFILE, --conffile CONFFILE
Conffile (default: .matrixbot.cfg)
-s SENDTO, --sendto SENDTO
Send to (default: no-reply@example.domain)
-d DAYS, --days DAYS  Days (default: 1)
```
Signed-off-by: Pablo Saavedra <psaavedra@igalia.com>

Add matrix-digest tool

---

matrixbot/matrix.py

The 'invite' and 'kick' commands can modify the list of room members. The patch forces a cache refresh if needed.
Signed-off-by: Javier M. Mellid <jmunhoz@igalia.com>

Fix memcache bug on 'invite' and 'kick' commands

---

matrixbot/matrix.py

The method `get_joined_members` returns a list of users without
keys, so it's no possible to break it down using the `keys()`
method anymore.
Instead iterate through the list and generate a new one containing only
the `user_id` of all members.
Closes #65

Fix invitations and kicks after upgrade

---

matrixbot/plugins/wkbotsfeeder.py

Also modify target step to `compile-jsc`, since this is a JSCOnly bot, and revamp test functions to improve visualization.

Replace JSCOnly MIPS bot for ARMv7
